var annotated_dup =
[
    [ "BigCloneFormater", "classBigCloneFormater.html", "classBigCloneFormater" ],
    [ "BigCloneTailorEvaluator", "classBigCloneTailorEvaluator.html", "classBigCloneTailorEvaluator" ],
    [ "CLIError", "classCLIError.html", "classCLIError" ],
    [ "CommandBase", "classCommandBase.html", "classCommandBase" ],
    [ "CommandNotFoundError", "classCommandNotFoundError.html", "classCommandNotFoundError" ],
    [ "Comparation", "structComparation.html", "structComparation" ],
    [ "Config", "classConfig.html", "classConfig" ],
    [ "ConsoleFormatter", "classConsoleFormatter.html", "classConsoleFormatter" ],
    [ "Context", "structContext.html", "structContext" ],
    [ "CounterDuplicationCode", "classCounterDuplicationCode.html", "classCounterDuplicationCode" ],
    [ "CounterDuplicationCodeTrie", "classCounterDuplicationCodeTrie.html", "classCounterDuplicationCodeTrie" ],
    [ "DuplicationFinderDiff", "classDuplicationFinderDiff.html", "classDuplicationFinderDiff" ],
    [ "DuplicationFinderTool", "classDuplicationFinderTool.html", "classDuplicationFinderTool" ],
    [ "FormatterManager", "classFormatterManager.html", null ],
    [ "Function", "classFunction.html", "classFunction" ],
    [ "FunctionBreaker", "classFunctionBreaker.html", "classFunctionBreaker" ],
    [ "FunctionBreakerC", "classFunctionBreakerC.html", "classFunctionBreakerC" ],
    [ "FunctionBreakerJava", "classFunctionBreakerJava.html", "classFunctionBreakerJava" ],
    [ "has_options", "structhas__options.html", null ],
    [ "has_options< T, std::void_t< decltype(T::options_)> >", "structhas__options_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1options___08_4_01_4.html", null ],
    [ "has_short_opts", "structhas__short__opts.html", null ],
    [ "has_short_opts< T, std::void_t< decltype(T::short_opts_)> >", "structhas__short__opts_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1short__opts___08_4_01_4.html", null ],
    [ "Help", "classHelp.html", "classHelp" ],
    [ "ICommand", "classICommand.html", "classICommand" ],
    [ "IFormatter", "classIFormatter.html", "classIFormatter" ],
    [ "Line_content", "structLine__content.html", "structLine__content" ],
    [ "OptionMissingError", "classOptionMissingError.html", "classOptionMissingError" ],
    [ "OptionsCollector", "classOptionsCollector.html", "classOptionsCollector" ],
    [ "Orchestrator", "classOrchestrator.html", "classOrchestrator" ],
    [ "ParsedOptions", "structParsedOptions.html", "structParsedOptions" ],
    [ "Parser", "classParser.html", "classParser" ],
    [ "Path", "classPath.html", "classPath" ],
    [ "Preprocessor", "classPreprocessor.html", "classPreprocessor" ],
    [ "RandomSelector", "classRandomSelector.html", "classRandomSelector" ],
    [ "SimilarFunctionFinder", "classSimilarFunctionFinder.html", "classSimilarFunctionFinder" ],
    [ "Similarity_Table", "classSimilarity__Table.html", "classSimilarity__Table" ],
    [ "SimilarityExplorer", "classSimilarityExplorer.html", "classSimilarityExplorer" ]
];